export enum SensorActionTypes {
  FETCH_SENSORS_REQUEST = 'FETCH_SENSORS_REQUEST',
  FETCH_SENSORS_SUCCESS = 'FETCH_SENSORS_SUCCESS',
  FETCH_SENSORS_FAILURE = 'FETCH_SENSORS_FAILURE',

  FETCH_SENSOR_BY_ID_REQUEST = 'FETCH_SENSOR_BY_ID_REQUEST',
  FETCH_SENSOR_BY_ID_SUCCESS = 'FETCH_SENSOR_BY_ID_SUCCESS',
  FETCH_SENSOR_BY_ID_FAILURE = 'FETCH_SENSOR_BY_ID_FAILURE',
}
