export enum CommonActionTypes {
  CHANGE_CURRENT_SPINDLE = 'CHANGE_CURRENT_SPINDLE',
  FETCH_SPINDLES_REQUEST = 'FETCH_SPINDLES_REQUEST',
  FETCH_SPINDLES_SUCCESS = 'FETCH_SPINDLES_SUCCESS',
  FETCH_SPINDLES_FAILURE = 'FETCH_SPINDLES_FAILURE',

  FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST',
  FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS',
  FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE',
}
