export enum IntrospectActionTypes {
  FETCH_INTROSPECT_REQUEST = 'FETCH_INTROSPECT_REQUEST',
  FETCH_INTROSPECT_SUCCESS = 'FETCH_INTROSPECT_SUCCESS',
  FETCH_INTROSPECT_FAILURE = 'FETCH_INTROSPECT_FAILURE',

  FETCH_INTROSPECT_BY_ID_REQUEST = 'FETCH_INTROSPECT_BY_ID_REQUEST',
  FETCH_INTROSPECT_BY_ID_SUCCESS = 'FETCH_INTROSPECT_BY_ID_SUCCESS',
  FETCH_INTROSPECT_BY_ID_FAILURE = 'FETCH_INTROSPECT_BY_ID_FAILURE',
}
