export enum SettingActionTypes {
  FETCH_PROFILE_DETAIL_REQUEST = 'FETCH_PROFILE_DETAIL_REQUEST',
  FETCH_PROFILE_DETAIL_SUCCESS = 'FETCH_PROFILE_DETAIL_SUCCESS',
  FETCH_PROFILE_DETAIL_FAILURE = 'FETCH_PROFILE_DETAIL_FAILURE',

  FETCH_SPINDLE_LIST_REQUEST = 'FETCH_SPINDLE_LIST_REQUEST',
  FETCH_SPINDLE_LIST_SUCCESS = 'FETCH_SPINDLE_LIST_SUCCESS',
  FETCH_SPINDLE_LIST_FAILURE = 'FETCH_SPINDLE_LIST_FAILURE',
}
